services:
  open-webui:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        INSTALL_PROFILE: ${INSTALL_PROFILE-core}
        PRELOAD_LOCAL_MODELS: ${PRELOAD_LOCAL_MODELS-false}
        ENABLE_PYODIDE: ${ENABLE_PYODIDE-false}
        VITE_SOURCEMAP: ${VITE_SOURCEMAP-false}
        HALO_RUNTIME_PROFILE: ${HALO_RUNTIME_PROFILE-main}
    image: ghcr.io/ztx888/halowebui:${WEBUI_DOCKER_TAG-main}
    container_name: open-webui
    volumes:
      - open-webui:/app/backend/data
    ports:
      - ${OPEN_WEBUI_PORT-3000}:8080
    environment:
      - 'WEBUI_SECRET_KEY='
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped

volumes:
  open-webui: {}
